export const HS_SECTION_LABELS_DE: Record<string, string> = {
  I: 'Lebende Tiere & tierische Erzeugnisse',
  II: 'Pflanzliche Erzeugnisse',
  III: 'Tierische und pflanzliche Fette und Ole',
  IV: 'Lebensmittel, Getranke, Tabak',
  V: 'Mineralische Stoffe & Brennstoffe',
  VI: 'Chemische Erzeugnisse',
  VII: 'Kunststoffe & Kautschuk',
  VIII: 'Leder, Pelze & Lederwaren',
  IX: 'Holz, Kork & Korbwaren',
  X: 'Papier, Pappe & Zellstoff',
  XI: 'Textilien & Bekleidung',
  XII: 'Schuhe, Kopfbedeckungen, Regenschirme',
  XIII: 'Steine, Keramik, Glas',
  XIV: 'Edelmetalle, Edelsteine, Schmuck',
  XV: 'Unedle Metalle & Metallwaren',
  XVI: 'Maschinen & elektrische Gerate',
  XVII: 'Fahrzeuge & Transportmittel',
  XVIII: 'Optik, Mess-, Medizingerate, Uhren',
  XIX: 'Waffen & Munition',
  XX: 'Mobel, Spielwaren, Sonstige',
  XXI: 'Kunstgegenstande & Antiquitaten',
  OTHER: 'Sonstige (nicht klassifiziert)',
}

export const HS_SECTION_LABELS_EN: Record<string, string> = {
  I: 'Live Animals & Animal Products',
  II: 'Vegetable Products',
  III: 'Animal & Vegetable Fats',
  IV: 'Food, Beverages, Tobacco',
  V: 'Minerals & Fuels',
  VI: 'Chemical Products',
  VII: 'Plastics & Rubber',
  VIII: 'Leather, Furs & Hides',
  IX: 'Wood, Cork & Basketware',
  X: 'Paper, Paperboard & Pulp',
  XI: 'Textiles & Apparel',
  XII: 'Footwear, Headgear, Umbrellas',
  XIII: 'Stone, Ceramics, Glass',
  XIV: 'Precious Metals & Stones',
  XV: 'Base Metals & Articles',
  XVI: 'Machinery & Electrical Equipment',
  XVII: 'Vehicles & Transport',
  XVIII: 'Optics, Measuring, Medical, Clocks',
  XIX: 'Arms & Ammunition',
  XX: 'Furniture, Toys, Misc.',
  XXI: 'Art & Antiques',
  OTHER: 'Other (unclassified)',
}
